### ISSUE TITLE
Card Limits

### ISSUE THREAD

**Issue by imdaveead** [reverse-squared/card-craze#138]
right now it says x / 50 charcter cards or whatever, but this not enforced at all anywhere.

two steps
- disable button.
- force server to not actually let you.

**Comment by hparcells** [comment]
Woah, I thought I did this. Maybe I'm misunderstanding something,

**Comment by hparcells** [comment]
![image](https://user-images.githubusercontent.com/40444294/60922652-3374be00-a26b-11e9-9b73-0ce977b42805.png)

Maybe the first step is done. Let's do the second.

**Comment by imdaveead** [comment]
oh i didnt know anyone added that, but i definetly know no one made the server reject it
