### ISSUE TITLE
Customizable Room Codes

### ISSUE THREAD

**Issue by hparcells** [reverse-squared/card-craze#2]
When someone wants to create a room, there could be an optional text field asking for a room code. If that meets the requirements, then the room with the room code they want is added.

Requirements:
- Room code is four characters. Lowercase letters will be converted to uppercase.
- Room code is not already taken.

**Comment by imdaveead** [comment]
i dont know, my main fear is the room codes being changed, and it makes it more confusing which code is valid, and also how the ui will look.

**Comment by hparcells** [comment]
Once the room is opened with a code it can’t be changed. Just to make it easier to work with.

**Comment by imdaveead** [comment]
where should the ui for the code go, i want to keep the simplicity of the "click and go" style the create room button is.
